### PR TITLE
Fix resigning for Enterprise env by removing beta-reports-active

### LINKED ISSUE #92: Issue when resigning app for Enterprise distribution
For Enterprise distribution, the `beta-reports-active` flag always has to be removed, as this is [only valid for App Store profiles](https://developer.apple.com/library/ios/qa/qa1830/_index.html).

Currently trying to install an .ipa resigned with an enterprise profile using `sigh resign` triggers the following error when trying to install it on a device:

```
installd <Error>: entitlement 'beta-reports-active' has value not permitted by provisioning profile '<enterprise provisioning profile name>'
installd <Error>: -[MICodeSigningVerifier performValidationWithError:]: 188: Failed to verify code signature of <MIExecutableBundle : path = /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.bwZuU7/extracted/Payload/... (Entitlements found that are not permitted by provisioning profile)
installd <Error>: -[MIInstaller performInstallationWithError:]: Verification stage failed
```

### PR DESCRIPTION
**Pull request by kommen**
This should fix #92

Would be nice if somebody who actually knows what they are doing could confirm that this is the correct fix. Also, this should probably be taken care of [upstream](https://github.com/nanonation/floatsign/) as well.

### CODE REVIEW

**Comment by milch** [comment]
There is already the `-r` option, maybe changing sigh to accept a parameter for that [here](https://github.com/KrauseFx/sigh/blob/master/lib/sigh/resign.rb#L29) would be more productive? I think the default of the `-r` option should be `no` anyway, since it breaks both enterprise and ad-hoc builds.

**Comment by kommen** [comment]
@milch As far as I see the `-r` option only affects if the `beta-reports-active` option is touched at all or not when resigning. But `resign.sh` assumes it should always be set to `YES` for Distribution builds. However, this assumption is not correct for Enterprise builds, which are not allowed to specify this flag.

**Comment by milch** [comment]
@kommen That is correct, if `-r` isn't set to `yes`, the `beta-reports-active` isn't touched at all. Since the addition of that parameter is handled by `resign` anyway (and it should only be present for TestFlight builds, not any other builds) doing anything else with it seems unnecessary. This is why, for the sake of simplicity and staying mostly on par with the upstream version of `floatsign`, I would keep that code as is and only add an additional configuration option to sigh for setting `-r`. 

Unless I'm missing something else why this needs to be handled explicitly.

**Comment by kommen** [comment]
@milch even if we'd add an option to not set `-r` for `resign.sh` the `beta-reports-active` could be present in the original .ipa and because it would not be touched would end up in the Enterprise .ipa, which is exactly what I ran into.

I agree, ideally we shouldn't have to change anything, except to update to a new `resign.sh` which handles this correctly. If you want to wait until this is handled upstream, thats fine too.

**Comment by kommen** [comment]
JFYI: https://github.com/nanonation/floatsign/pull/5

**Comment by KrauseFx** [comment]
Thanks @kommen :+1:

**Pull request merged**
