### PR TITLE
Resign dylibs in FRAMEWORKS_DIR to make resigned Swift apps run

### LINKED ISSUE #93: Resigned apps which use Swift crash on launch
Apps which are (partially) built with Swift and then are resigned with `sigh resign` will crash on launch because of invalid code-signing of the Swift libraries in the .ipa.

The app crashes with the following printed to the log
```
amfid <Error>: /private/var/mobile/Containers/Bundle/Application/527A6055-B847-4505-89ED-D916A7B01C3E/My App.app/Frameworks/libswiftCore.dylib not valid: 0xe8008015: A valid provisioning profile for this executable was not found.
```

This is printed when during resigning:
```
Resigning embedded frameworks using certificate: 'iPhone Distribution: my GmbH'
Ignoring non-framework: _floatsignTemp/Payload/My APp.app/Frameworks/libswiftCore.dylib
Ignoring non-framework: _floatsignTemp/Payload/My APp.app/Frameworks/libswiftCoreGraphics.dylib
Ignoring non-framework: _floatsignTemp/Payload/My APp.app/Frameworks/libswiftCoreImage.dylib
Ignoring non-framework: _floatsignTemp/Payload/My APp.app/Frameworks/libswiftDarwin.dylib
Ignoring non-framework: _floatsignTemp/Payload/My APp.app/Frameworks/libswiftDispatch.dylib
Ignoring non-framework: _floatsignTemp/Payload/My APp.app/Frameworks/libswiftFoundation.dylib
Ignoring non-framework: _floatsignTemp/Payload/My APp.app/Frameworks/libswiftObjectiveC.dylib
Ignoring non-framework: _floatsignTemp/Payload/My APp.app/Frameworks/libswiftSecurity.dylib
Ignoring non-framework: _floatsignTemp/Payload/My APp.app/Frameworks/libswiftUIKit.dylib
```

This is probably the issue tracked here: https://github.com/nanonation/floatsign/issues/4

### PR DESCRIPTION
**Pull request by kommen**
This fixes #93

### CODE REVIEW

**Comment by KrauseFx** [comment]
Thank you @kommen! I'll publish a new release today! :+1:

**Comment by mdakram** [comment]
@KrauseFx @kommen this PR is targeting dylibs files in framework folder only. Which is not a ideal case i think.

**Comment by kommen** [comment]
@mdakram can you elaborate? Are you running into specific troubles?

**Comment by mdakram** [comment]
@kommen actually in my ipa there is no framework folder, all dylib files are under $TEMP_DIR/Payload/$APP_NAME/

**Comment by kommen** [comment]
@mdakram Interesting. I'm not sure if there's a "best practice" for where the dylibs should go, but for all my apps they go into the frameworks folder. However, I don't see any reason why resigning should be limited to the Frameworks folder.

**Comment by mdakram** [comment]
@kommen yup that was my point.

**Pull request merged**
