### PR TITLE
Added signing identity option

### PR DESCRIPTION
**Pull request by sp-miguel-ibero**
Added command line option to be able to select the signing identity when resigning.

### CODE REVIEW

**Comment by KrauseFx** [comment]
But this option is already available: 
```
sigh resign --help
```

```
    -i, --signing_identity STRING
        The signing identity to use. Must match the one defined in the provisioning profile.

    -p, --provisioning_profile STRING
        The path to the provisioning profile which should be used
```

**Comment by sp-miguel-ibero** [comment]
Yes you're right. I checked again and the problem is that the `-i` option is colliding with the generic `cert_id` option when calling resign and `options.signing_identity` is never set

```
sigh resign GJ01.ipa -i "MS5UR3KX42" -p app.mobileprovision
<Commander::Command::Options cert_id="MS5UR3KX42", provisioning_name="app.mobileprovision", provisioning_profile="app.mobileprovision">
```

**Comment by chrisvire** [comment]
@sp-miguel-ibero, how do you get the output of `<Commander::Command::Options ... />`?  I am having the same problem with `-i` option.

**Comment by chrisvire** [comment]
This is a known issue (`-i` not working, use `--signing_identity` instead).  See #69.

**Comment by ohwutup** [comment]
hey @sp-miguel-ibero, thanks for the PR! does it make more sense to just update this option to use `-s` instead of `-i`?
https://github.com/fastlane/sigh/pull/97/files#diff-f044611a46e8e3cc86a7ed08ba17517eR68

**Comment by ohwutup** [comment]
hey @sp-miguel-ibero, haven't heard back in a while, going to close this for now.

**Pull request closed without merging**
