### PR TITLE
Allow resign script to adjust `beta-reports-active`

### PR DESCRIPTION
**Pull request by tonyxiao**
Addresses issue #64

### CODE REVIEW

**Comment by KrauseFx** [comment]
:+1:

**Comment by tonyxiao** [comment]
@KrauseFx quick question, when can I expect this to make it into the installable gem? How does that process work anyway?

**Comment by KrauseFx** [comment]
I have to do a release. I usually wait until there are 2-3 changes, as it always takes some time to prepare. In the meantime, just download the repository and run `sudo bundle install` and `sudo rake install`.

**Comment by wireframe** [comment]
just my 2 cents, but I'm hitting the same issue and having a bug fix release with this change would be really awesome.  i understand not wanting to do a release for every pull request, but this is a pretty huge one for me.  i'm not sure how folks are actually getting builds into testflight without this change?

**Comment by KrauseFx** [comment]
Give me 5 minutes :wink:

**Comment by KrauseFx** [comment]
Here we go: https://github.com/KrauseFx/sigh/releases/tag/0.4.7 Let me know if that solves the issue :+1:

**Pull request merged**
