### PR TITLE
Fix issue with resigning apps with nested watchkit app and extension

### PR DESCRIPTION
**Pull request by mgrebenets**
See #265 for more details
Just fixing up CBBundleIdentifier for each nested app or extension
is not enough
Must also fix references from WatchKit app to companion app
and from WatchKit extension to WatchKit app

### CODE REVIEW

**Comment by asfalcone** [comment]
@kommen @baarde Would you mind helping me out by taking a look at this PR? Thanks 🎁

**Comment by kommen** [comment]
I don't have a WatchKit app at hand where I use resign, so I can't test this PR.

The change looks good to me though.

**Comment by asfalcone** [comment]
@mgrebenets thanks for the PR!  @kommen thanks for the review!  :rocket:  :watch:

**Comment by mgrebenets** [comment]
Thanks @kommen @asfalcone :+1: 

Since we are at it, I have a few questions with regards to `resign.sh`.
Do you guys know why most, if not all, of the `echo` commands are writing to `stderr` via `>&2`?
It's not critical, but CI servers like Team City treat these messages as warnings this way, while the messages are just normal logs.

**Comment by asfalcone** [comment]
@mgrebenets not sure unfortunately. could you submit this question as an issue and we'll see if we can figure it out? Thanks!

**Comment by mgrebenets** [comment]
Sure, done https://github.com/fastlane/sigh/issues/268.

**Pull request merged**
